export { default as Main } from './Main/Main'
export { default as Nav } from './Nav/Nav'
export { default as Hero } from './Hero/Hero'
export { default as Links } from './Links/Links'
export { default as CV } from './Links/CV/CV'
export { default as Portfolio } from './Links/Portfolio/Portfolio'
export { default as QandA } from './Links/QandA/QandA'
